-- MySQL Script generated by MySQL Workbench
-- Fri Nov 28 16:25:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `Telefone_id` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`, `Telefone_id`),
  INDEX `fk_Cliente_Telefone1_idx` (`Telefone_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Telefone1`
    FOREIGN KEY (`Telefone_id`)
    REFERENCES `mydb`.`Telefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `id` INT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `data_pagamento` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `valor_pago` INT NULL,
  `forma_pagamento` ENUM('pix', 'debito', 'credito', 'boleto') NULL,
  `status_pagamento` ENUM('cancelado', 'pendente', 'concluido', 'recusado') NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `id` INT NOT NULL,
  `placa` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(32) NOT NULL,
  `marca` VARCHAR(20) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ano` YEAR(4) NOT NULL,
  `Cliente_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Cliente_id`),
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nome` VARCHAR(20) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `pecas_utilizadas` VARCHAR(45) NULL,
  `custo` VARCHAR(45) NULL,
  `data_inicio` DATETIME NULL,
  `data__conclu` DATETIME NULL,
  `Pagamento_id` VARCHAR(32) NOT NULL,
  `Veiculo_id` VARCHAR(16) NOT NULL,
  `Veiculo_Cliente_id` VARCHAR(45) NOT NULL,
  `Funcionario_id` INT NOT NULL,
  `Funcionario_Funcionario_id` INT NOT NULL,
  `Funcionario_id1` INT NOT NULL,
  `Funcionario_Funcionario_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `Pagamento_id`, `Funcionario_id`, `Funcionario_Funcionario_id`, `Funcionario_id1`, `Funcionario_Funcionario_id1`),
  INDEX `fk_Ordem de Serviço_Pagamento_idx` (`Pagamento_id` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Veiculo1_idx` (`Veiculo_id` ASC, `Veiculo_Cliente_id` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Funcionario1_idx` (`Funcionario_id` ASC, `Funcionario_Funcionario_id` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Funcionario2_idx` (`Funcionario_id1` ASC, `Funcionario_Funcionario_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Pagamento`
    FOREIGN KEY (`Pagamento_id`)
    REFERENCES `mydb`.`Pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Veiculo1`
    FOREIGN KEY (`Veiculo_id` , `Veiculo_Cliente_id`)
    REFERENCES `mydb`.`Veiculo` (`id` , `Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Funcionario1`
    FOREIGN KEY (`Funcionario_id`)
    REFERENCES `mydb`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Funcionario2`
    FOREIGN KEY (`Funcionario_id1`)
    REFERENCES `mydb`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status de Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status de Pagamento` (
  `Cancelado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Pendente` TIMESTAMP NULL,
  `Concluido` VARCHAR(45) NULL,
  `Recusado` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(45) NULL,
  `Cliente_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Cliente_id`),
  INDEX `fk_Usuario_Cliente1_idx` (`Cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `id` VARCHAR(20) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nome` VARCHAR(20) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `id` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nome_peca` TIMESTAMP NULL,
  `quantidade_estoque` VARCHAR(45) NULL,
  `preco_unitario` VARCHAR(45) NULL,
  `Ordem de Serviço_id` INT NOT NULL,
  `Ordem de Serviço_Pagamento_id` VARCHAR(32) NOT NULL,
  `Fornecedor_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `Fornecedor_id`),
  INDEX `fk_Peças_Ordem de Serviço1_idx` (`Ordem de Serviço_id` ASC, `Ordem de Serviço_Pagamento_id` ASC) VISIBLE,
  INDEX `fk_Peças_Fornecedor1_idx` (`Fornecedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Peças_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_id` , `Ordem de Serviço_Pagamento_id`)
    REFERENCES `mydb`.`Ordem de Serviço` (`id` , `Pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peças_Fornecedor1`
    FOREIGN KEY (`Fornecedor_id`)
    REFERENCES `mydb`.`Fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
